/*******************************************************************************
 * Copyright (c) 2020 Asmakam Inc.
 ******************************************************************************/

/**
* @Author               :       rahulchaudharyofficial@outlook.com
* @description          :       Exception class thats thrown when user do not 
                                have access to record(s)
* @since                :       1.0.0
* @version              :       1.0.0
*/
public inherited sharing class UserRecordAccessException extends Exception {}